//
//  HKWorkoutActivityType+String.swift
//  InBody_HealthKit
//
//  Created by 장선영 on 2022/04/28.
//

import HealthKit

extension HKWorkoutActivityType {
    var stringRepresentation: String {
        switch self {
        case .archery: return "archery"
        case .bowling: return "bowling"
        case .fencing: return "fencing"
        case .gymnastics: return "gymnastics"
        case .trackAndField: return "trackAndField"
        case .americanFootball: return "americanFootball"
        case .australianFootball: return "australianFootball"
        case .baseball: return "baseball"
        case .basketball: return "basketball"
        case .cricket: return "cricket"
        case .discSports: return "discSports"
        case .handball: return "handball"
        case .hockey: return "hockey"
        case .lacrosse: return "lacrosse"
        case .rugby: return "rugby"
        case .soccer: return "soccer"
        case .softball: return "softball"
        case .volleyball: return "volleyball"
        case .preparationAndRecovery: return "preparationAndRecovery"
        case .flexibility: return "flexibility"
        case .cooldown: return "cooldown"
        case .walking: return "walking"
        case .running: return "running"
        case .badminton: return "badminton"
        case .boxing: return "boxing"
        case .climbing: return "climbing"
        case .crossTraining: return "crossTraining"
        case .curling: return "curling"
        case .cycling: return "cycling"
        case .dance: return "dance"
        case .danceInspiredTraining: return "danceInspiredTraining"
        case .elliptical: return "elliptical"
        case .equestrianSports: return "equestrianSports"
        case .fishing: return "fishing"
        case .functionalStrengthTraining: return "functionalStrengthTraining"
        case .golf: return "golf"
        case .hiking: return "hiking"
        case .hunting: return "hunting"
        case .martialArts: return "martialArts"
        case .mindAndBody: return "mindAndBody"
        case .mixedMetabolicCardioTraining: return "mixedMetabolicCardioTraining"
        case .paddleSports: return "paddleSports"
        case .play: return "play"
        case .racquetball: return "racquetball"
        case .rowing: return "rowing"
        case .sailing: return "sailing"
        case .skatingSports: return "skatingSports"
        case .snowSports: return "snowSports"
        case .squash: return "squash"
        case .stairClimbing: return "stairClimbing"
        case .surfingSports: return "surfingSports"
        case .swimming: return "swimming"
        case .tableTennis: return "tableTennis"
        case .tennis: return "tennis"
        case .traditionalStrengthTraining: return "traditionalStrengthTraining"
        case .waterFitness: return "waterFitness"
        case .waterPolo: return "waterPolo"
        case .waterSports: return "waterSports"
        case .wrestling: return "wrestling"
        case .yoga: return "yoga"
        case .barre: return "barre"
        case .coreTraining: return "coreTraining"
        case .crossCountrySkiing: return "crossCountrySkiing"
        case .downhillSkiing: return "downhillSkiing"
        case .highIntensityIntervalTraining: return "highIntensityIntervalTraining"
        case .jumpRope: return "jumpRope"
        case .kickboxing: return "kickboxing"
        case .pilates: return "pilates"
        case .snowboarding: return "snowboarding"
        case .stairs: return "stairs"
        case .stepTraining: return "stepTraining"
        case .wheelchairWalkPace: return "wheelchairWalkPace"
        case .wheelchairRunPace: return "wheelchairRunPace"
        case .taiChi: return "taiChi"
        case .mixedCardio: return "mixedCardi"
        case .handCycling: return "handCycling"
        case .fitnessGaming: return "fitnessGaming"
        case .cardioDance: return "cardioDance"
        case .socialDance: return "socialDance"
        case .pickleball: return "pickleball"
        case .other: return "other"
        }
    }
}
